name: ZOOC PR CI

on:
  pull_request:
    branches: [ develop, main ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build:
    name: PR Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Ktlint
        run: ./gradlew ktlintCheck

      - name: Test with Gradle
        run: ./gradlew test

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: build/test-results/**/*.xml

      - name: On Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#53A551'
          SLACK_ICON: https://user-images.githubusercontent.com/59532818/197379133-676094c1-d544-4784-b582-60e061f69d31.png?size=48
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: 'ZOOC Android CI checks have passed ✅'
          MSG_MINIMAL: true
          SLACK_USERNAME: 쭉쭉빵빵
          SLACK_MESSAGE: 'PR check 쭉쭉빵빵하게 성공 😎😎😎'

      - name: On Failed, Notify in Slack
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: '#ff0000'
          SLACK_ICON: https://user-images.githubusercontent.com/59532818/197379133-676094c1-d544-4784-b582-60e061f69d31.png?size=48
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: 'ZOOC Android CI checks have failed 🚫'
          MSG_MINIMAL: true
          SLACK_USERNAME: 쭉쭉빵빵
          SLACK_MESSAGE: 'WHAT THE BUG'